language: ruby
rvm:
  - 2.0.0
  env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/travis.database.yml config/database.yml
  - psql -c 'create database todo_test' -U postgres


notifications:
  webhooks: https://api.kato.im/rooms/cf8800459ff629021013f1f988cd6642b5289991e24cc62854e1d08e3a7d810/travis