# check the format with travis-lint gem
#  travis-lint .travis.yml

language: node_js
node_js:
  - 0.8
language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql
script:
  - "bundle exec rake travis:run"
  - karma start --single-run --browsers PhantomJS jstest/config.coffee
before_script:
  - cp config/travis.database.yml config/database.yml
  - psql -c 'create database todo_test' -U postgres
  - npm install
  - npm install karma

#push to kato
notifications:
  webhooks: https://api.kato.im/rooms/cf8800459ff629021013f1f988cd6642b5289991e24cc62854e1d08e3a7d810/travis